### ISSUE TITLE
Latest Build

### ISSUE THREAD

**Issue by someguylarry** [Arks-Layer/PSO2TweakerV4#3]
Hey Arks Layer crew,

Mind releasing the latest source?

Yours Truly,

Larry

**Comment by Aida-Enna** [comment]
Hey Larry,

You didn't keep your end of the bargain by removing the website per "Removal Scheduled 2017-05-27 @ 12:00PM US EST pending good behavior."

Since you were unable to keep your promise to me, I see no need to release any further source code. Additionally, you were asked to cease all further contact with me or any member of our team, and infact asked us *not* to contact you. Therefore, any further contact on your part will be considered harassment and the proper administration for that avenue will be notified.

Thank you for your support, and have a nice day.
